/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/00cfa2d0-a8ef-442a-8ec3-8f715cab254f 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float acmeDistance;
  float acmeHumidity;
  float acmeTemp;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <DHT.h>

// Pin definitions
#define DHTPIN 12         // DHT11 data pin
#define DHTTYPE DHT11     // DHT 11 sensor type
#define TRIG_PIN 2        // HC-SR04 Trig pin
#define ECHO_PIN 3        // HC-SR04 Echo pin

// Create DHT sensor object
DHT dht(DHTPIN, DHTTYPE);

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);

    // Initialize DHT sensor
  dht.begin();

  // Set trig pin as output and echo pin as input
  pinMode(TRIG_PIN, OUTPUT);
  pinMode(ECHO_PIN, INPUT);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  if (isnan(acmeHumidity) || isnan(acmeTemp)) {
  Serial.println("Failed to read from DHT sensor!");
} else {
  // Update cloud variables
  acmeHumidity = dht.readHumidity();
  acmeTemp = dht.readTemperature();
}
  // Measure temperature and humidity

  Serial.print("Humidity: ");
  Serial.print(acmeHumidity);
  Serial.print("%  Temperature: ");
  Serial.print(acmeTemp);
  Serial.println("C");

  // Measure distance using HC-SR04
  long duration;

  // Send a 10us pulse to trigger pin
  digitalWrite(TRIG_PIN, LOW);
  delayMicroseconds(2);
  digitalWrite(TRIG_PIN, HIGH);
  delayMicroseconds(10);
  digitalWrite(TRIG_PIN, LOW);

  // Read the echo pin to get duration of pulse
  duration = pulseIn(ECHO_PIN, HIGH);

  // Calculate distance in cm
  acmeDistance = (duration * 0.0343) / 2;

  // Print distance to serial monitor
  Serial.print("Distance: ");
  Serial.print(acmeDistance);
  Serial.println(" cm");

  // Wait before repeating measurements
  delay(2000);
}




/*
  Since AcmeTemp is READ_WRITE variable, onAcmeTempChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onAcmeTempChange()  {
  // Add your code here to act upon AcmeTemp change
}

/*
  Since AcmeHumidity is READ_WRITE variable, onAcmeHumidityChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onAcmeHumidityChange()  {
  // Add your code here to act upon AcmeHumidity change
}

/*
  Since AcmeDistance is READ_WRITE variable, onAcmeDistanceChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onAcmeDistanceChange()  {
  // Add your code here to act upon AcmeDistance change
}
